select * from ny_bg_variables_table;
--15403

--Build tags 

create table acs_computed.ny_bg_variables_table_enhanced as
  select distinct uc.name as county_name, uc.geoid, z.intersects_zip, cs.intersects_county_subdivision, nbvt.*, st_x(st_centroid(bg.geom)) as x,
  st_y(st_centroid(bg.geom)) as y
  from 
     ny_bg_variables_table nbvt join spatial.tl_2013_36_bg  bg on nbvt.geoid_tiger = bg.geoid
     join spatial.us_counties uc on St_intersects(bg.geom, uc.geom) and uc.geoid = left(bg.geoid,5)

  join (
    select bg.geoid,  
      array_agg(distinct cs.name) as intersects_county_subdivision
    from spatial.tl_2013_36_bg bg join spatial.tl_2013_36_cousub cs on st_intersects(cs.geom, bg.geom) group by bg.geoid) cs 
  on cs.geoid = nbvt.geoid_tiger
  join (
    select bg.geoid,  
      array_agg(distinct cs.geoid10) as intersects_zip
    from spatial.tl_2013_36_bg bg join spatial.tl_2013_us_zcta510 cs on st_intersects(cs.geom, bg.geom) group by bg.geoid) z
  on z.geoid = nbvt.geoid_tiger;
  
  /*
  select * from (
  select case when g1.geoid < g2.geoid then g1.geoid else null end as geoid1, case when g1.geoid < g2.geoid then g2.geoid end as geoid2
    from spatial.tl_2013_36_bg g1 join spatial.tl_2013_36_bg g2 on
      g1.geoid != g2.geoid and st_touches(g1.geom, g2.geom)) t where geoid1 is not null;
 */

CREATE TABLE acs_computed.ny_bg_variables_insurance_enhanced
AS
   SELECT nbe.county_name,
          nbe.geoid,
          nbe.intersects_zip,
          nbe.intersects_county_subdivision,
          nbe.geo_name,
          nbe.full_geoid,
          nbe.geoid_tiger,
          nbe.total_population,
          nbe.land_area_square_meters,
          nbe.population_density_per_square_kilometer,
          nbe.total_population_non_hispanic,
          nbe.total_population_hispanic,
          nbe.fraction_population_non_hispanic,
          nbe.fraction_population_hispanic,
          nbe.total_households,
          nbe.spanish_language_households,
          nbe.fraction_spanish_language_households,
          nbe.english_language_households,
          nbe.fraction_english_language_households,
          nbe.median_age,
          nbe.median_household_income_2013,
          nbe.per_capita_income_2013,
          nbe.total_households_receiving_snap,
          nbe.total_households_with_one_disability,
          nbe.fraction_receiving_snap,
          nbe.fraction_with_one_disability,
          nbe.total_households_owner_occupied,
          nbe.total_households_renter_occupied,
          nbe.fraction_households_owner_occupied,
          nbe.fraction_households_renter_occupied,
          nbe.total,
          nbe.total_white,
          nbe.total_african_american,
          nbe.total_native_american,
          nbe.total_asian_american,
          nbe.total_two_or_more_races,
          nbe.fraction_population_white,
          nbe.fraction_population_african_american,
          nbe.fraction_population_native_american,
          nbe.fraction_population_asian_american,
          nbe.fraction_population_two_or_more_races,
          nbe.geom,
          nbe.geom_geojson,
          nbe.x,
          nbe.y,
          nbi.fraction_no_health_insurance_64,
          nbi.fraction_no_health_insurance,
          nbi.fraction_medicaid_any_64,
          nbi.fraction_medicaid_any,
          nbi.medicaid_any_64,
          nbi.medicaid_any,
          nbi.medicare_any_64,
          nbi.medicare_any_65_plus,
          nbi.medicare_only,
          nbi.medicare_only_64,
          nbi.medicaid_only_64,
          nbi.population_64,
          nbi.no_health_insurance_64,
          nbi.no_health_insurance,
          nbi.medicare_medicaid,
          nbi.medicare_medicaid_64,
          nbi.medicare_employee_64,
          nbi.medicare_employee,
          nbi.population_total,
          nbi.population_17,
          nbi.medicare_only_17,
          nbi.medicaid_only_17,
          nbi.medicare_employee_17,
          nbi.medicare_medicaid_17,
          nbi.no_health_insurance_17,
          nbi.population_18_34,
          nbi.medicare_only_18_34,
          nbi.medicaid_only_18_34,
          nbi.medicare_employee_18_34,
          nbi.medicare_medicaid_18_34,
          nbi.no_health_insurance_18_34,
          nbi.population_35_64,
          nbi.medicare_only_35_64,
          nbi.medicaid_only_35_64,
          nbi.medicare_employee_35_64,
          nbi.medicare_direct_purchase_35_64,
          nbi.medicare_medicaid_35_64,
          nbi.no_health_insurance_35_64,
          nbi.population_65_plus,
          nbi.medicare_only_65_plus,
          nbi.medicare_employee_65_plus,
          nbi.medicare_direct_purchase_65_plus,
          nbi.medicare_medicaid_65_plus,
          nbi.no_health_insurance_65_plus
     FROM acs_computed.ny_bg_variables_table_enhanced nbe
          JOIN acs_computed.ny_bg_insurance_2013 nbi
             ON nbi.geoid_tiger = nbe.geoid_tiger;


SELECT ngbvi.county_name,
       ngbvi.geoid,
       ngbvi.intersects_zip,
       ngbvi.intersects_county_subdivision,
       ngbvi.geo_name,
       ngbvi.full_geoid,
       ngbvi.geoid_tiger,
       ngbvi.total_population,
       ngbvi.land_area_square_meters,
       ngbvi.population_density_per_square_kilometer,
       ngbvi.total_population_non_hispanic,
       ngbvi.total_population_hispanic,
       ngbvi.fraction_population_non_hispanic,
       ngbvi.fraction_population_hispanic,
       ngbvi.total_households,
       ngbvi.spanish_language_households,
       ngbvi.fraction_spanish_language_households,
       ngbvi.english_language_households,
       ngbvi.fraction_english_language_households,
       ngbvi.median_age,
       ngbvi.median_household_income_2013,
       ngbvi.per_capita_income_2013,
       ngbvi.total_households_receiving_snap,
       ngbvi.total_households_with_one_disability,
       ngbvi.fraction_receiving_snap,
       ngbvi.fraction_with_one_disability,
       ngbvi.total_households_owner_occupied,
       ngbvi.total_households_renter_occupied,
       ngbvi.fraction_households_owner_occupied,
       ngbvi.fraction_households_renter_occupied,
       ngbvi.total,
       ngbvi.total_white,
       ngbvi.total_african_american,
       ngbvi.total_native_american,
       ngbvi.total_asian_american,
       ngbvi.total_two_or_more_races,
       ngbvi.fraction_population_white,
       ngbvi.fraction_population_african_american,
       ngbvi.fraction_population_native_american,
       ngbvi.fraction_population_asian_american,
       ngbvi.fraction_population_two_or_more_races,
       ngbvi.x,
       ngbvi.y,
       ngbvi.fraction_no_health_insurance_64,
       ngbvi.fraction_no_health_insurance,
       ngbvi.fraction_medicaid_any_64,
       ngbvi.fraction_medicaid_any,
       ngbvi.medicaid_any_64,
       ngbvi.medicaid_any,
       ngbvi.medicare_any_64,
       ngbvi.medicare_any_65_plus,
       ngbvi.medicare_only,
       ngbvi.medicare_only_64,
       ngbvi.medicaid_only_64,
       ngbvi.population_64,
       ngbvi.no_health_insurance_64,
       ngbvi.no_health_insurance,
       ngbvi.medicare_medicaid,
       ngbvi.medicare_medicaid_64,
       ngbvi.medicare_employee_64,
       ngbvi.medicare_employee,
       ngbvi.population_total,
       ngbvi.population_17,
       ngbvi.medicare_only_17,
       ngbvi.medicaid_only_17,
       ngbvi.medicare_employee_17,
       ngbvi.medicare_medicaid_17,
       ngbvi.no_health_insurance_17,
       ngbvi.population_18_34,
       ngbvi.medicare_only_18_34,
       ngbvi.medicaid_only_18_34,
       ngbvi.medicare_employee_18_34,
       ngbvi.medicare_medicaid_18_34,
       ngbvi.no_health_insurance_18_34,
       ngbvi.population_35_64,
       ngbvi.medicare_only_35_64,
       ngbvi.medicaid_only_35_64,
       ngbvi.medicare_employee_35_64,
       ngbvi.medicare_direct_purchase_35_64,
       ngbvi.medicare_medicaid_35_64,
       ngbvi.no_health_insurance_35_64,
       ngbvi.population_65_plus,
       ngbvi.medicare_only_65_plus,
       ngbvi.medicare_employee_65_plus,
       ngbvi.medicare_direct_purchase_65_plus,
       ngbvi.medicare_medicaid_65_plus,
       ngbvi.no_health_insurance_65_plus
  FROM acs_computed.ny_bg_variables_insurance_enhanced ngbvi
  where ngbvi.county_name in ('Suffolk', 'Nassau');
  ;
